name: bondnet_new_test
channels:
  - conda-forge
  - defaults
dependencies:
  - intel-openmp
  - libgcc-ng=13.2.0
  - mkl=2024.0.0
  - openbabel=3.1.1
  - python=3.11.7
  - setuptools=68.2.2
  - pip:
      - babel==2.14.0
      - bson==0.5.10
      - dgl==1.1.3+cu121
      - lightning==2.1.2
      - lightning-utilities==0.10.0
      - lmdb==1.4.1
      - matplotlib==3.8.2
      - monty==2023.11.3
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.1.4
      - pebble==5.0.5
      - plotly==5.18.0
      - psutil==5.9.7
      - pymatgen==2023.12.18
      - python-dateutil==2.8.2
      - pytorch-lightning==2.1.2
      - rdkit-pypi==2022.9.5
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - tabulate==0.9.0
      - tenacity==8.2.3
      - threadpoolctl==3.2.0
      - torch==2.1.2
      - torchmetrics==0.11.1
      - tqdm==4.66.1
      - wandb==0.15.3
      - yarl==1.9.4
